// <auto-generated />
using System;
using LingoToneMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LingoToneMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612083508_AddQuizResults")]
    partial class AddQuizResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LingoToneMVC.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequiredXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("LingoToneMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LingoToneMVC.Models.ChineseCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HanViet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Radical")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChineseCharacters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Character = "你",
                            HanViet = "nhĩ",
                            HskLevel = "HSK1",
                            Meaning = "bạn",
                            Pinyin = "nǐ",
                            Radical = "亻",
                            StrokeCount = 7
                        },
                        new
                        {
                            Id = 2,
                            Character = "好",
                            HanViet = "hảo",
                            HskLevel = "HSK1",
                            Meaning = "tốt",
                            Pinyin = "hǎo",
                            Radical = "女",
                            StrokeCount = 6
                        },
                        new
                        {
                            Id = 3,
                            Character = "我",
                            HanViet = "ngã",
                            HskLevel = "HSK1",
                            Meaning = "tôi",
                            Pinyin = "wǒ",
                            Radical = "戈",
                            StrokeCount = 7
                        },
                        new
                        {
                            Id = 4,
                            Character = "叫",
                            HanViet = "khiếu",
                            HskLevel = "HSK1",
                            Meaning = "tên là",
                            Pinyin = "jiào",
                            Radical = "口",
                            StrokeCount = 5
                        },
                        new
                        {
                            Id = 5,
                            Character = "是",
                            HanViet = "thị",
                            HskLevel = "HSK1",
                            Meaning = "là",
                            Pinyin = "shì",
                            Radical = "日",
                            StrokeCount = 9
                        },
                        new
                        {
                            Id = 6,
                            Character = "学",
                            HanViet = "học",
                            HskLevel = "HSK1",
                            Meaning = "học",
                            Pinyin = "xué",
                            Radical = "子",
                            StrokeCount = 8
                        },
                        new
                        {
                            Id = 7,
                            Character = "生",
                            HanViet = "sinh",
                            HskLevel = "HSK1",
                            Meaning = "sinh viên",
                            Pinyin = "shēng",
                            Radical = "生",
                            StrokeCount = 5
                        },
                        new
                        {
                            Id = 8,
                            Character = "老",
                            HanViet = "lão",
                            HskLevel = "HSK1",
                            Meaning = "già",
                            Pinyin = "lǎo",
                            Radical = "老",
                            StrokeCount = 6
                        },
                        new
                        {
                            Id = 9,
                            Character = "师",
                            HanViet = "sư",
                            HskLevel = "HSK1",
                            Meaning = "thầy",
                            Pinyin = "shī",
                            Radical = "巾",
                            StrokeCount = 6
                        },
                        new
                        {
                            Id = 10,
                            Character = "喜",
                            HanViet = "hỷ",
                            HskLevel = "HSK2",
                            Meaning = "thích",
                            Pinyin = "xǐ",
                            Radical = "口",
                            StrokeCount = 12
                        },
                        new
                        {
                            Id = 11,
                            Character = "欢",
                            HanViet = "hoan",
                            HskLevel = "HSK2",
                            Meaning = "vui",
                            Pinyin = "huān",
                            Radical = "欠",
                            StrokeCount = 6
                        },
                        new
                        {
                            Id = 12,
                            Character = "吃",
                            HanViet = "ngật",
                            HskLevel = "HSK1",
                            Meaning = "ăn",
                            Pinyin = "chī",
                            Radical = "口",
                            StrokeCount = 6
                        },
                        new
                        {
                            Id = 13,
                            Character = "喝",
                            HanViet = "hát",
                            HskLevel = "HSK2",
                            Meaning = "uống",
                            Pinyin = "hē",
                            Radical = "口",
                            StrokeCount = 12
                        },
                        new
                        {
                            Id = 14,
                            Character = "去",
                            HanViet = "khứ",
                            HskLevel = "HSK1",
                            Meaning = "đi",
                            Pinyin = "qù",
                            Radical = "厶",
                            StrokeCount = 5
                        },
                        new
                        {
                            Id = 15,
                            Character = "来",
                            HanViet = "lai",
                            HskLevel = "HSK1",
                            Meaning = "đến",
                            Pinyin = "lái",
                            Radical = "人",
                            StrokeCount = 7
                        });
                });

            modelBuilder.Entity("LingoToneMVC.Models.DailyMissionClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MissionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("XpAwarded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyMissionClaims");
                });

            modelBuilder.Entity("LingoToneMVC.Models.FlashCard", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MeaningEnglish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MeaningVietnamese")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CardId");

                    b.ToTable("FlashCards");
                });

            modelBuilder.Entity("LingoToneMVC.Models.GrammarPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExampleMeaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExamplePinyin")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("GrammarPoints");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Example = "我是学生。",
                            ExampleMeaning = "Tôi là học sinh.",
                            ExamplePinyin = "Wǒ shì xuéshēng.",
                            LessonId = 1,
                            Pattern = "S + 是 + N",
                            Title = "是 (shì) - Là"
                        },
                        new
                        {
                            Id = 2,
                            Example = "我不是老师。",
                            ExampleMeaning = "Tôi không phải giáo viên.",
                            ExamplePinyin = "Wǒ bù shì lǎoshī.",
                            LessonId = 2,
                            Pattern = "S + 不 + V",
                            Title = "不 (bù) - Phủ định"
                        },
                        new
                        {
                            Id = 3,
                            Example = "你是学生吗？",
                            ExampleMeaning = "Bạn là học sinh phải không?",
                            ExamplePinyin = "Nǐ shì xuéshēng ma?",
                            LessonId = 2,
                            Pattern = "S + V + O + 吗？",
                            Title = "吗 (ma) - Câu hỏi Yes/No"
                        },
                        new
                        {
                            Id = 4,
                            Example = "我呢？",
                            ExampleMeaning = "Còn tôi thì sao?",
                            ExamplePinyin = "Wǒ ne?",
                            LessonId = 2,
                            Pattern = "N + 呢？",
                            Title = "呢 (ne) - Còn...thì sao?"
                        },
                        new
                        {
                            Id = 5,
                            Example = "我有一个苹果。",
                            ExampleMeaning = "Tôi có một quả táo.",
                            ExamplePinyin = "Wǒ yǒu yī ge píngguǒ.",
                            LessonId = 4,
                            Pattern = "S + 有 + N",
                            Title = "有 (yǒu) - Có"
                        },
                        new
                        {
                            Id = 6,
                            Example = "我喜欢看书。",
                            ExampleMeaning = "Tôi thích đọc sách.",
                            ExamplePinyin = "Wǒ xǐhuān kàn shū.",
                            LessonId = 5,
                            Pattern = "S + 喜欢 + V/N",
                            Title = "喜欢 (xǐhuān) - Thích"
                        },
                        new
                        {
                            Id = 7,
                            Example = "三个学生",
                            ExampleMeaning = "Ba học sinh",
                            ExamplePinyin = "sān ge xuéshēng",
                            LessonId = 3,
                            Pattern = "Số + Lượng từ + N",
                            Title = "数词 + 量词 - Số đếm"
                        },
                        new
                        {
                            Id = 8,
                            Example = "你去哪里？",
                            ExampleMeaning = "Bạn đi đâu?",
                            ExamplePinyin = "Nǐ qù nǎlǐ?",
                            LessonId = 8,
                            Pattern = "S + 去 + Địa điểm",
                            Title = "去 (qù) - Đi đến"
                        });
                });

            modelBuilder.Entity("LingoToneMVC.Models.GrammarRule", b =>
                {
                    b.Property<int>("GrammarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrammarId"));

                    b.Property<string>("ExampleChinese")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExamplePinyin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExampleVietnamese")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("GrammarId");

                    b.HasIndex("LessonId");

                    b.ToTable("GrammarRules");
                });

            modelBuilder.Entity("LingoToneMVC.Models.HskWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExampleChinese")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExamplePinyin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExampleVietnamese")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MeaningEnglish")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MeaningVietnamese")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Radical")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StrokeCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HskWords");
                });

            modelBuilder.Entity("LingoToneMVC.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Giới thiệu bản thân và chào hỏi cơ bản",
                            HskLevel = "",
                            ImageUrl = "/images/lesson1.jpg",
                            OrderIndex = 1,
                            Title = "Bài 1: Chào hỏi"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giới thiệu nghề nghiệp và bản thân",
                            HskLevel = "",
                            ImageUrl = "/images/lesson2.jpg",
                            OrderIndex = 2,
                            Title = "Bài 2: Giới thiệu"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Học các số đếm cơ bản trong tiếng Trung",
                            HskLevel = "",
                            ImageUrl = "/images/lesson3.jpg",
                            OrderIndex = 3,
                            Title = "Bài 3: Số đếm"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Giới thiệu và nói về các thành viên trong gia đình",
                            HskLevel = "",
                            ImageUrl = "/images/lesson4.jpg",
                            OrderIndex = 4,
                            Title = "Bài 4: Gia đình"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Diễn đạt sở thích và hoạt động yêu thích",
                            HskLevel = "",
                            ImageUrl = "/images/lesson5.jpg",
                            OrderIndex = 5,
                            Title = "Bài 5: Sở thích"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Học cách hỏi giá và mua đồ",
                            HskLevel = "",
                            ImageUrl = "/images/lesson6.jpg",
                            OrderIndex = 6,
                            Title = "Bài 6: Mua sắm"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Học cách hỏi và nói về thời gian",
                            HskLevel = "",
                            ImageUrl = "/images/lesson7.jpg",
                            OrderIndex = 7,
                            Title = "Bài 7: Thời gian"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Học cách hỏi đường và các phương tiện đi lại",
                            HskLevel = "",
                            ImageUrl = "/images/lesson8.jpg",
                            OrderIndex = 8,
                            Title = "Bài 8: Đi lại"
                        });
                });

            modelBuilder.Entity("LingoToneMVC.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XpReward")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "A",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "你好 / nǐ hǎo / nghĩa là xin chào.",
                            LessonId = 1,
                            OptionA = "Xin chào",
                            OptionB = "Tạm biệt",
                            OptionC = "Cảm ơn",
                            OptionD = "Xin lỗi",
                            Question = "\"你好\" có nghĩa là gì?",
                            QuestionType = "Vocabulary",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "谢谢 đọc là xiè xie, nghĩa là cảm ơn.",
                            LessonId = 1,
                            OptionA = "nǐ hǎo",
                            OptionB = "zài jiàn",
                            OptionC = "xiè xie",
                            OptionD = "duì bu qǐ",
                            Question = "Pinyin của từ \"谢谢\" là gì?",
                            QuestionType = "Vocabulary",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "再见 / zài jiàn / nghĩa là tạm biệt.",
                            LessonId = 1,
                            OptionA = "Xin lỗi",
                            OptionB = "Tạm biệt",
                            OptionC = "Không sao",
                            OptionD = "Rất tốt",
                            Question = "\"再见\" nghĩa là gì?",
                            QuestionType = "Vocabulary",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "C",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "一 đọc là yī, nghĩa là số một.",
                            LessonId = 1,
                            OptionA = "èr",
                            OptionB = "sān",
                            OptionC = "yī",
                            OptionD = "wǔ",
                            Question = "Số \"一\" đọc là gì?",
                            QuestionType = "Vocabulary",
                            XpReward = 20
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "B",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Explanation = "我是学生 / wǒ shì xué shēng / nghĩa là Tôi là học sinh.",
                            LessonId = 1,
                            OptionA = "Tôi là giáo viên",
                            OptionB = "Tôi là học sinh",
                            OptionC = "Bạn là học sinh",
                            OptionD = "Bạn là giáo viên",
                            Question = "\"我是学生\" có nghĩa là gì?",
                            QuestionType = "Grammar",
                            XpReward = 20
                        });
                });

            modelBuilder.Entity("LingoToneMVC.Models.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("XPGained")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("LingoToneMVC.Models.RoleplayScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExpectedDialogue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RoleplayScenarios");
                });

            modelBuilder.Entity("LingoToneMVC.Models.SrsCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SrsLevel")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SrsCards");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserDailyLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDailyLogins");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserLearnedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LearnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLearnedWords");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletionPercent")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStudyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.Property<int>("XpEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserQuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuizAttempts");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserSrsReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SrsCardId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSrsReviews");
                });

            modelBuilder.Entity("LingoToneMVC.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chinese")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Vietnamese")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Vocabularies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Chinese = "你",
                            LessonId = 1,
                            Pinyin = "nǐ",
                            Vietnamese = "bạn, anh, chị"
                        },
                        new
                        {
                            Id = 2,
                            Chinese = "好",
                            LessonId = 1,
                            Pinyin = "hǎo",
                            Vietnamese = "tốt, được"
                        },
                        new
                        {
                            Id = 3,
                            Chinese = "你好",
                            LessonId = 1,
                            Pinyin = "nǐ hǎo",
                            Vietnamese = "xin chào"
                        },
                        new
                        {
                            Id = 4,
                            Chinese = "我",
                            LessonId = 1,
                            Pinyin = "wǒ",
                            Vietnamese = "tôi, mình"
                        },
                        new
                        {
                            Id = 5,
                            Chinese = "叫",
                            LessonId = 1,
                            Pinyin = "jiào",
                            Vietnamese = "tên là, gọi là"
                        },
                        new
                        {
                            Id = 6,
                            Chinese = "是",
                            LessonId = 2,
                            Pinyin = "shì",
                            Vietnamese = "là"
                        },
                        new
                        {
                            Id = 7,
                            Chinese = "老师",
                            LessonId = 2,
                            Pinyin = "lǎoshī",
                            Vietnamese = "giáo viên, thầy giáo"
                        },
                        new
                        {
                            Id = 8,
                            Chinese = "学生",
                            LessonId = 2,
                            Pinyin = "xuéshēng",
                            Vietnamese = "học sinh, sinh viên"
                        },
                        new
                        {
                            Id = 9,
                            Chinese = "吗",
                            LessonId = 2,
                            Pinyin = "ma",
                            Vietnamese = "trợ từ câu hỏi"
                        },
                        new
                        {
                            Id = 10,
                            Chinese = "呢",
                            LessonId = 2,
                            Pinyin = "ne",
                            Vietnamese = "còn...thì sao?"
                        },
                        new
                        {
                            Id = 11,
                            Chinese = "一",
                            LessonId = 3,
                            Pinyin = "yī",
                            Vietnamese = "một"
                        },
                        new
                        {
                            Id = 12,
                            Chinese = "二",
                            LessonId = 3,
                            Pinyin = "èr",
                            Vietnamese = "hai"
                        },
                        new
                        {
                            Id = 13,
                            Chinese = "三",
                            LessonId = 3,
                            Pinyin = "sān",
                            Vietnamese = "ba"
                        },
                        new
                        {
                            Id = 14,
                            Chinese = "四",
                            LessonId = 3,
                            Pinyin = "sì",
                            Vietnamese = "bốn"
                        },
                        new
                        {
                            Id = 15,
                            Chinese = "五",
                            LessonId = 3,
                            Pinyin = "wǔ",
                            Vietnamese = "năm"
                        },
                        new
                        {
                            Id = 16,
                            Chinese = "爸爸",
                            LessonId = 4,
                            Pinyin = "bàba",
                            Vietnamese = "bố, ba"
                        },
                        new
                        {
                            Id = 17,
                            Chinese = "妈妈",
                            LessonId = 4,
                            Pinyin = "māma",
                            Vietnamese = "mẹ, má"
                        },
                        new
                        {
                            Id = 18,
                            Chinese = "哥哥",
                            LessonId = 4,
                            Pinyin = "gēge",
                            Vietnamese = "anh trai"
                        },
                        new
                        {
                            Id = 19,
                            Chinese = "姐姐",
                            LessonId = 4,
                            Pinyin = "jiějie",
                            Vietnamese = "chị gái"
                        },
                        new
                        {
                            Id = 20,
                            Chinese = "弟弟",
                            LessonId = 4,
                            Pinyin = "dìdi",
                            Vietnamese = "em trai"
                        },
                        new
                        {
                            Id = 21,
                            Chinese = "喜欢",
                            LessonId = 5,
                            Pinyin = "xǐhuān",
                            Vietnamese = "thích, yêu thích"
                        },
                        new
                        {
                            Id = 22,
                            Chinese = "看书",
                            LessonId = 5,
                            Pinyin = "kàn shū",
                            Vietnamese = "đọc sách"
                        },
                        new
                        {
                            Id = 23,
                            Chinese = "听音乐",
                            LessonId = 5,
                            Pinyin = "tīng yīnyuè",
                            Vietnamese = "nghe nhạc"
                        },
                        new
                        {
                            Id = 24,
                            Chinese = "运动",
                            LessonId = 5,
                            Pinyin = "yùndòng",
                            Vietnamese = "thể dục, vận động"
                        },
                        new
                        {
                            Id = 25,
                            Chinese = "电影",
                            LessonId = 5,
                            Pinyin = "diànyǐng",
                            Vietnamese = "phim, điện ảnh"
                        },
                        new
                        {
                            Id = 26,
                            Chinese = "多少钱",
                            LessonId = 6,
                            Pinyin = "duōshao qián",
                            Vietnamese = "bao nhiêu tiền?"
                        },
                        new
                        {
                            Id = 27,
                            Chinese = "贵",
                            LessonId = 6,
                            Pinyin = "guì",
                            Vietnamese = "đắt"
                        },
                        new
                        {
                            Id = 28,
                            Chinese = "便宜",
                            LessonId = 6,
                            Pinyin = "piányí",
                            Vietnamese = "rẻ"
                        },
                        new
                        {
                            Id = 29,
                            Chinese = "买",
                            LessonId = 6,
                            Pinyin = "mǎi",
                            Vietnamese = "mua"
                        },
                        new
                        {
                            Id = 30,
                            Chinese = "卖",
                            LessonId = 6,
                            Pinyin = "mài",
                            Vietnamese = "bán"
                        },
                        new
                        {
                            Id = 31,
                            Chinese = "几点",
                            LessonId = 7,
                            Pinyin = "jǐ diǎn",
                            Vietnamese = "mấy giờ?"
                        },
                        new
                        {
                            Id = 32,
                            Chinese = "现在",
                            LessonId = 7,
                            Pinyin = "xiànzài",
                            Vietnamese = "bây giờ, hiện tại"
                        },
                        new
                        {
                            Id = 33,
                            Chinese = "上午",
                            LessonId = 7,
                            Pinyin = "shàngwǔ",
                            Vietnamese = "buổi sáng"
                        },
                        new
                        {
                            Id = 34,
                            Chinese = "下午",
                            LessonId = 7,
                            Pinyin = "xiàwǔ",
                            Vietnamese = "buổi chiều"
                        },
                        new
                        {
                            Id = 35,
                            Chinese = "晚上",
                            LessonId = 7,
                            Pinyin = "wǎnshang",
                            Vietnamese = "buổi tối"
                        },
                        new
                        {
                            Id = 36,
                            Chinese = "去",
                            LessonId = 8,
                            Pinyin = "qù",
                            Vietnamese = "đi (tới)"
                        },
                        new
                        {
                            Id = 37,
                            Chinese = "哪里",
                            LessonId = 8,
                            Pinyin = "nǎlǐ",
                            Vietnamese = "ở đâu, đâu"
                        },
                        new
                        {
                            Id = 38,
                            Chinese = "怎么",
                            LessonId = 8,
                            Pinyin = "zěnme",
                            Vietnamese = "như thế nào, bằng cách nào"
                        },
                        new
                        {
                            Id = 39,
                            Chinese = "公交",
                            LessonId = 8,
                            Pinyin = "gōngjiāo",
                            Vietnamese = "xe buýt công cộng"
                        },
                        new
                        {
                            Id = 40,
                            Chinese = "地铁",
                            LessonId = 8,
                            Pinyin = "dìtiě",
                            Vietnamese = "tàu điện ngầm (metro)"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LingoToneMVC.Models.DailyMissionClaim", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.GrammarPoint", b =>
                {
                    b.HasOne("LingoToneMVC.Models.Lesson", "Lesson")
                        .WithMany("GrammarPoints")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LingoToneMVC.Models.GrammarRule", b =>
                {
                    b.HasOne("LingoToneMVC.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LingoToneMVC.Models.QuizQuestion", b =>
                {
                    b.HasOne("LingoToneMVC.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("LingoToneMVC.Models.QuizResult", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.SrsCard", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany("SrsCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserDailyLogin", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserLearnedWord", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany("LearnedWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserProgress", b =>
                {
                    b.HasOne("LingoToneMVC.Models.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserQuizAttempt", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.UserSrsReview", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LingoToneMVC.Models.Vocabulary", b =>
                {
                    b.HasOne("LingoToneMVC.Models.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LingoToneMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LingoToneMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LingoToneMVC.Models.ApplicationUser", b =>
                {
                    b.Navigation("LearnedWords");

                    b.Navigation("SrsCards");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("LingoToneMVC.Models.Lesson", b =>
                {
                    b.Navigation("GrammarPoints");

                    b.Navigation("UserProgresses");

                    b.Navigation("Vocabularies");
                });
#pragma warning restore 612, 618
        }
    }
}
